<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scrap.Domain</RootNamespace>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>true</ImplicitUsings>
    <AssemblyName>Scrap.Domain</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Basic.Reference.Assemblies.Net80" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.CodeAnalysis" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" />
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting" />
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Polly" />
    <PackageReference Include="SharpX" />
    <PackageReference Include="System.Linq.Async" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\FileSystem\TemplateDestinationProvider.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
    <Compile Remove="Resources\FileSystem\TemplateDestinationProvider.cs"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Scrap.Tests.Unit</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
