<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Scrap.Common</RootNamespace>
    <LangVersion>12</LangVersion>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>Nullable</WarningsAsErrors>
    <IsPackable>false</IsPackable>
    <ImplicitUsings>true</ImplicitUsings>
    <AssemblyName>Scrap.Common</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ben.demystifier" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="SharpX" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

</Project>
